Label2Numbers:
  Healthy: 0
  OA: 2
  Peri-OA: 1
cv_configs:
  num_splits: 5
  random_seed: 42
downsample_rate: 10
gesture_list:
- Key Pinch
- Stat Abd
- Stat Add
- Stat Ext
- Stat Flex
gt_path: /project/ahoover/mhealth/zeyut/tmc/TMC AI Files/ProcessedData/gt.pkl
image_model_configs:
  batch_size: 4
  gt_type: bony
  learning_rate: 0.001
  max_step: 30
  num_epochs: 20
  num_workers: 4
  patience: 3
  seed_path: /project/ahoover/mhealth/zeyut/tmc/pre_trained/swin_unetr_btcv_segmentation/models/model.pt
kinematic_channels:
- helical_angle
- helical_translation
- volar-dorsal_angle
- volar-dorsal_translation
- radial-ulnar_angle
- radial-ulnar_translation
- inferior-superior_angle
- inferior-superior_translation
kinematic_model_configs:
  batch_size: 8
  beta: 0.9999
  constrastive_margin: 0.2
  gt_type: kinematic
  learning_rate: 0.001
  max_step: 50
  num_epochs: 10
  num_workers: 4
  patience: 3
  top_k: 3
processed_data_path: /project/ahoover/mhealth/zeyut/tmc/TMC AI Files/ProcessedData
raw_data_path: /project/ahoover/mhealth/zeyut/tmc/TMC AI Files/Data
results_path: /project/ahoover/mhealth/zeyut/tmc/results/
root_path: /project/ahoover/mhealth/zeyut/tmc/TMC AI Files
target_cycle_len: 12000
